<html>
<head>
	<title>FAQ3</title>
</head>
<body>
	<?php
	include('topnav.php');
	?>
<div class="article-indent">
	<table width="100%" border="0" bgcolor="#FFFFFF">
<tr>
	<td colspan="4" height="23" align="left" valign="middle" class="rowBorder">&nbsp;<strong>&nbsp;&nbsp;&nbsp;</strong>	  <h1><strong>What to do in faulty investigation ?..... </strong></h1></td>
</tr>
<div class="article-separator-indent"><span 
	class="article_separator">&nbsp;</span></div>
<tr>
  <td height="20" colspan="4"></td>
</tr>
<tr>
	<td height="20" colspan="4" valign="middle"><ul>
	  <li>
	    <p align="justify">In case of faulty investigation application can be submitted to concerned DSP Investigation, SP Investigation or DPO. For the purpose of change of investigation application can be submitted in the DPO Office which will be considered in the meeting of the committee for change of investigation.</p>
	  </li>
	  </ul></td>
</tr>
<tr>
</body>
</html>